name: agenda_slim
description: A new Flutter project.

# ################
publish_to: 'none' 

# #################
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# #################
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  get_it: 5.0.6
  path: 
  mobx: 1.2.1+4
  flutter_mobx: ^1.1.0+2
  mask_text_input_formatter: ^1.2.1
  url_launcher: 5.7.10
  




  # ################
  cupertino_icons: ^1.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.11.1
  mobx_codegen: 1.1.2


  # ###################
  flutter_lints: ^1.0.0

# ####################
flutter:

  # ##################
  uses-material-design: true

  # ##################